name: roots_of_life
description: A Flutter app to explore different mangrove species.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/red_mangrove.png
    - assets/images/black_mangrove.png
    - assets/images/mangrove_logo.png
    - assets/images/seamangrove_bg.png
    - assets/images/sonneratia.png
    - assets/images/bruguiera.png
    - assets/images/nipa.png
    - assets/images/grey_mangrove.png
    - assets/images/white_mangrove.png
    - assets/images/kandelia.png
    - assets/images/ceriops.png
    - assets/images/lumnitzera.png
    - assets/images/excoecaria.png
    - assets/images/aegiceras.png
    - assets/images/rhizophora_mucronata.png
    - assets/images/bruguiera_gymnorrhiza.png
    - assets/images/rhizophora_apiculata.png
    - assets/images/avicennia_alba.png
    - assets/images/ceriops_decandra.png
    - assets/images/xylocarpus_granatum.png
    - assets/images/lumnitzera_littorea.png
    - assets/images/bruguiera_sexangula.png
    - assets/images/mangrove_logo.png
    - assets/images/seamangrove_bg.png